version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v1.3.0
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: guest
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_JWT_SECRET: {"type": "HS256", "key": "my_jwt_secret"}
      ACTION_HANDLER_URL: "http://host.docker.internal:3000"
  docmate:
    image: djyde/docmate:latest
    ports:
      - "3000:3000"
    depends_on:
      - "graphql-engine"
    restart: always
    volumes:
      - ./data/docmate:/data
    environment:

 